name: docker-markhazletonsample

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Show Docker info
      run: docker info

    - name: Show Buildx version
      run: docker buildx version

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Mwh.Sample.Web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mwhsampleweb:latest, ${{ secrets.DOCKERHUB_USERNAME }}/mwhsampleweb:${{ github.run_number }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
