name: docker-markhazletonsample

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint --ignore DL3008 < ./Mwh.Sample.Web/Dockerfile

      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ hashFiles('**/Dockerfile', '**/Mwh.Sample.Web/**/*') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Show Docker info
        run: docker info

      - name: Show Buildx version
        run: docker buildx version

      - name: Build and push
        id: docker_image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Mwh.Sample.Web/Dockerfile
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mwhsampleweb:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mwhsampleweb:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Cleanup
        run: |
          docker builder prune -f
          docker system prune -f

      - name: Set Docker Image Output
        run: echo "image=${{ secrets.DOCKERHUB_USERNAME }}/mwhsampleweb:latest" >> $GITHUB_ENV
        shell: bash
